# Generated by Django 6.0.4 on 2026-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set this higher than price to show a discount.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Percentage discount (e.g., 20 for 20%)')),
                ('active', models.BooleanField(default=True)),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Select specific products this code applies to. Leave empty to apply to the whole cart.', related_name='promo_codes', to='store.product')),
            ],
        ),
    ]
