# Generated by Django 6.0.4 on 2026-05-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_offer_product_original_price_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_clearance',
            field=models.BooleanField(default=False, help_text='Check to display in the Stock Clearance zone.'),
        ),
    ]
