# Generated by Django 6.0.4 on 2026-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_clearance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable deliveries to this pincode.')),
            ],
        ),
    ]
